//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _307_3073105_search_bing_png_logo_burger_king_logo_png {
            get {
                object obj = ResourceManager.GetObject("307-3073105_search-bing-png-logo-burger-king-logo-png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _329_3292041_pepsi_logo_logo_de_pepsi_png_clipart {
            get {
                object obj = ResourceManager.GetObject("329-3292041_pepsi-logo-logo-de-pepsi-png-clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _368_3688927_mcdonalds_logo_png_mcdonalds_logo_png_clipart {
            get {
                object obj = ResourceManager.GetObject("368-3688927_mcdonalds-logo-png-mcdonalds-logo-png-clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _580b57fcd9996e24bc43c1dc {
            get {
                object obj = ResourceManager.GetObject("580b57fcd9996e24bc43c1dc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _584298bca6515b1e0ad75adc {
            get {
                object obj = ResourceManager.GetObject("584298bca6515b1e0ad75adc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _58429977a6515b1e0ad75ade {
            get {
                object obj = ResourceManager.GetObject("58429977a6515b1e0ad75ade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _587187927b7f6103e35c6cd5 {
            get {
                object obj = ResourceManager.GetObject("587187927b7f6103e35c6cd5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _58737bd3f3a71010b5e8ef37 {
            get {
                object obj = ResourceManager.GetObject("58737bd3f3a71010b5e8ef37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _79_796596_energy_clipart_logo_monster_energy_logo_png_transparent {
            get {
                object obj = ResourceManager.GetObject("79-796596_energy-clipart-logo-monster-energy-logo-png-transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap descarga {
            get {
                object obj = ResourceManager.GetObject("descarga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kissclipart_burger_king_clipart_hamburger_burger_king_breakfas_1338b389d16938b0 {
            get {
                object obj = ResourceManager.GetObject("kissclipart-burger-king-clipart-hamburger-burger-king-breakfas-1338b389d16938b0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_lamborghini_logo_brand_fellow_agp_motorsport_5b80de31bf5a22_1504908715351721457838 {
            get {
                object obj = ResourceManager.GetObject("kisspng-lamborghini-logo-brand-fellow-agp-motorsport-5b80de31bf5a22.1504908715351" +
                        "721457838", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_logo_logitech_anyangle_carrying_case_flip_for_ip_logitech_zskv_rekordnch_devt_ocenn_i_5b6f9e05a5f472_2409633115340416056798 {
            get {
                object obj = ResourceManager.GetObject("kisspng-logo-logitech-anyangle-carrying-case-flip-for-ip-logitech-zskv-rekordnch-" +
                        "devt-ocenn-i-5b6f9e05a5f472.2409633115340416056798", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_pepsi_fizzy_drinks_mountain_dew_coca_cola_carbonat_mountain_dew_5acc32d02c5e45_4350263915233317921817 {
            get {
                object obj = ResourceManager.GetObject("kisspng-pepsi-fizzy-drinks-mountain-dew-coca-cola-carbonat-mountain-dew-5acc32d02" +
                        "c5e45.4350263915233317921817", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Razer {
            get {
                object obj = ResourceManager.GetObject("Razer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
